name: {{cookiecutter.project_dir}}
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytest=7.4.0  
  - mlflow=2.5.0
  - ipykernel=6.28.0
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - cudatoolkit-dev
  - pip:
    - tensorflow==2.10

    